// frontend/web-app/app/nav/Navbar.tsx
import React from 'react';
import Search from '@/app/nav/Search';
import Logo from '@/app/nav/Logo';
import LoginButton from '@/app/nav/LoginButton';

export default function Navbar() {
  return (
    <header className='sticky top-0 z-50 flex justify-between bg-white p-5 items-center text-gray-800 shadow-md'>
      <Logo />
      <Search />
      <LoginButton />
    </header>
  );
}

// frontend/qwik-app/src/components/nav/Navbar.tsx
import { component$ } from '@builder.io/qwik';
import Logo from '~/components/nav/Logo';
import Search from '~/components/nav/Search';
import LoginButton from '~/components/nav/LoginButton';

export default component$(() => {
  return (
    <header class='sticky top-0 z-50 flex justify-between bg-white p-5 items-center text-gray-800 shadow-md'>
      <Logo />
      <Search />
      <LoginButton />
    </header>
  );
});
