// frontend/qwik-app/src/components/auctions/CountdownTimer.tsx
import { component$, useSignal } from '@builder.io/qwik';

export default component$<{ auctionEnd: string }>(({ auctionEnd }) => {
  const completed = useSignal<boolean>(false);
  const days = 10;
  const hours = 9;

  return (
    <div>
      <div
        class={`
        border-2 
        border-white 
        text-white 
        py-1 
        px-2 
        rounded-lg 
        flex 
        justify-center
        ${
          completed.value
            ? 'bg-red-600'
            : days === 0 && hours < 10
            ? 'bg-amber-600'
            : 'bg-green-600'
        }
      `}
      ></div>
    </div>
  );
});

// frontend/web-app/app/auctions/CountdownTimer.tsx
'use client';

import React from 'react';
import Countdown, { zeroPad } from 'react-countdown';

type Props = {
  auctionEnd: string;
};

const renderer = ({
  days,
  hours,
  minutes,
  seconds,
  completed,
}: {
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
  completed: boolean;
}) => {
  return (
    <div
      className={`
    border-2 border-white text-white py-1 px-2 rounded-lg flex justify-center
    ${
      completed
        ? 'bg-red-600'
        : days === 0 && hours < 10
        ? 'bg-amber-600'
        : 'bg-green-600'
    }
    `}
    >
      {completed ? (
        <span>Auction finished</span>
      ) : (
        <span suppressHydrationWarning>
          {zeroPad(days)}:{zeroPad(hours)}:{zeroPad(minutes)}:{zeroPad(seconds)}
        </span>
      )}
    </div>
  );
};

export default function CountdownTimer({ auctionEnd }: Props) {
  return (
    <div>
      <Countdown date={auctionEnd} renderer={renderer} />
    </div>
  );
}
