// frontend/qwik-app/src/components/auctions/Filters.tsx
import { component$ } from '@builder.io/qwik';
import { BsStopwatchFill, BsStopCircleFill } from '@qwikest/icons/bootstrap';
import {
  HiFireMini,
  HiShieldExclamationMini,
  HiClockOutline,
} from '@qwikest/icons/heroicons';
import SortAscending from '~/components/icons/SortAscending';

const pageSizeButtons = [4, 8, 12];

const orderButtons = [
  {
    label: 'Alphabetical',
    icon: SortAscending,
    value: 'make',
  },
  {
    label: 'End date',
    icon: HiClockOutline,
    value: 'endingSoon',
  },
  {
    label: 'Recently added',
    icon: BsStopCircleFill,
    value: 'new',
  },
];

const filterButtons = [
  {
    label: 'Live auctions',
    icon: HiFireMini,
    value: 'live',
  },
  {
    label: 'Ending < 6 hours',
    icon: HiShieldExclamationMini,
    value: 'endingSoon',
  },
  {
    label: 'Completed',
    icon: BsStopwatchFill,
    value: 'finished',
  },
];

export default component$(() => {
  const filterBy = 'live';
  const orderBy = 'make';
  const pageSize = 4;

  return (
    <div class='flex justify-between items-center mb-4'>
      <div>
        <span class='uppercase text-sm text-gray-500 mr-2'>Filter by</span>
        <div class='inline-flex rounded-md shadow-sm' role='group'>
          {filterButtons.map(({ label, icon: Icon, value }, index: number) => (
            <button
              key={value}
              class={[
                'inline-flex',
                'items-center',
                'px-4',
                'py-2',
                'text-sm',
                'font-medium',
                'text-gray-900',
                'bg-white',
                'border-gray-200',
                'hover:bg-gray-100',
                'focus:z-10',
                'focus:ring-2',
                'first-of-type:rounded-l-lg',
                'last-of-type:rounded-r-md',
                index === 0 || index === filterButtons.length - 1
                  ? 'border'
                  : 'border-t border-b',
                {
                  'text-red-900 border-red-300 enabled:hover:bg-red-100 focus:ring-4 focus:ring-red-300 :bg-red-600 focus:text-red-900':
                    filterBy === value,
                },
              ]}
            >
              <Icon class='mr-3 h-4 w-4' />
              {label}
            </button>
          ))}
        </div>
      </div>
      <div>
        <span class='uppercase text-sm text-gray-500 mr-2'>Order by</span>
        <div class='inline-flex rounded-md shadow-sm' role='group'>
          {orderButtons.map(({ label, icon: Icon, value }, index: number) => (
            <button
              key={value}
              class={[
                'inline-flex',
                'items-center',
                'px-4',
                'py-2',
                'text-sm',
                'font-medium',
                'text-gray-900',
                'bg-white',
                'border-gray-200',
                'hover:bg-gray-100',
                'hover:cyan-blue-700',
                'focus:z-10',
                'focus:ring-2',
                'first-of-type:rounded-l-lg',
                'last-of-type:rounded-r-md',
                index === 0 || index === orderButtons.length - 1
                  ? 'border'
                  : 'border-t border-b',
                {
                  'text-red-900 border-red-300 enabled:hover:bg-red-100 focus:ring-4 focus:ring-red-300 :bg-red-600 focus:text-red-900':
                    orderBy === value,
                },
              ]}
            >
              <Icon class='mr-3 h-4 w-4' />
              {label}
            </button>
          ))}
        </div>
      </div>
      <div>
        <span class='uppercase text-sm text-gray-500 mr-2'>Page size</span>
        <div class='inline-flex rounded-md shadow-sm' role='group'>
          {pageSizeButtons.map((value: number, index: number) => (
            <button
              key={value}
              class={[
                'inline-flex',
                'items-center',
                'px-4',
                'py-2',
                'text-sm',
                'font-medium',
                'text-gray-900',
                'bg-white',
                'border-gray-200',
                'hover:bg-gray-100',
                'hover:cyan-blue-700',
                'focus:z-10',
                'focus:ring-2',
                'first-of-type:rounded-l-lg',
                'last-of-type:rounded-r-md',
                index === 0 || index === orderButtons.length - 1
                  ? 'border'
                  : 'border-t border-b',
                {
                  'text-red-900 border-red-300 enabled:hover:bg-red-100 focus:ring-4 focus:ring-red-300 :bg-red-600 focus:text-red-900':
                    pageSize === value,
                },
              ]}
            >
              {value}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
});

// frontend/web-app/app/auctions/Filters.tsx
import React from 'react';
import { Button } from 'flowbite-react';
import { useParamsStore } from '@/app/hooks/useParamsStore';
import { AiOutlineClockCircle, AiOutlineSortAscending } from 'react-icons/ai';
import { BsFillStopCircleFill, BsStopwatchFill } from 'react-icons/bs';
import { GiFinishLine, GiFlame } from 'react-icons/gi';

const pageSizeButtons = [4, 8, 12];

const orderButtons = [
  {
    label: 'Alphabetical',
    icon: AiOutlineSortAscending,
    value: 'make',
  },
  {
    label: 'End date',
    icon: AiOutlineClockCircle,
    value: 'endingSoon',
  },
  {
    label: 'Recently added',
    icon: BsFillStopCircleFill,
    value: 'new',
  },
];

const filterButtons = [
  {
    label: 'Live auctions',
    icon: GiFlame,
    value: 'live',
  },
  {
    label: 'Ending < 6 hours',
    icon: GiFinishLine,
    value: 'endingSoon',
  },
  {
    label: 'Completed',
    icon: BsStopwatchFill,
    value: 'finished',
  },
];

export default function Filters() {
  const pageSize = useParamsStore((state) => state.pageSize);
  const setParams = useParamsStore((state) => state.setParams);
  const orderBy = useParamsStore((state) => state.orderBy);
  const filterBy = useParamsStore((state) => state.filterBy);

  return (
    <div className='flex justify-between items-center mb-4'>
      <div>
        <span className='uppercase text-sm text-gray-500 mr-2'>Filter by</span>
        <Button.Group>
          {filterButtons.map(({ label, icon: Icon, value }) => (
            <Button
              key={value}
              onClick={() => setParams({ filterBy: value })}
              color={filterBy === value ? 'red' : 'gray'}
            >
              <Icon className='mr-3 h-4 w-4' />
              {label}
            </Button>
          ))}
        </Button.Group>
      </div>
      <div>
        <span className='uppercase text-sm text-gray-500 mr-2'>Order by</span>
        <Button.Group>
          {orderButtons.map(({ label, icon: Icon, value }) => (
            <Button
              key={value}
              onClick={() => setParams({ orderBy: value })}
              color={orderBy === value ? 'red' : 'gray'}
            >
              <Icon className='mr-3 h-4 w-4' />
              {label}
            </Button>
          ))}
        </Button.Group>
      </div>
      <div>
        <span className='uppercase text-sm text-gray-500 mr-2'>Page size</span>
        <Button.Group>
          {pageSizeButtons.map((value) => (
            <Button
              key={value}
              onClick={() => setParams({ pageSize: value })}
              color={pageSize === value ? 'red' : 'gray'}
              className='focus:ring-0'
            >
              {value}
            </Button>
          ))}
        </Button.Group>
      </div>
    </div>
  );
}
