// frontend/qwik-app/src/components/auctions/Listings.tsx
import {
  Resource,
  component$,
  useContext,
  useResource$,
} from '@builder.io/qwik';
import { getData } from '~/server/auctions';
import type { Auction, PagedResult } from '~/types';
import AppPagination from '~/components/shared/AppPagination';
import AuctionCard from '~/components/auctions/AuctionCard';
import EmptyFilter from '~/components/shared/EmptyFilter';
import Filters from '~/components/auctions/Filters';
import { searchContext } from '~/store/searchAuctions';

export default component$(() => {
  const searchStore = useContext(searchContext);

  const data = useResource$<PagedResult<Auction>>(async ({ track }) => {
    track(() => [
      searchStore.filterBy,
      searchStore.orderBy,
      searchStore.pageNumber,
      searchStore.pageSize,
      searchStore.searchTerm,
    ]);

    let queryString = `?orderBy=${searchStore.orderBy}&filterBy=${searchStore.filterBy}&pageSize=${searchStore.pageSize}&pageNumber=${searchStore.pageNumber}`;

    if (searchStore.searchTerm) {
      queryString += `&searchTerm=${searchStore.searchTerm}`;
    }

    const result: PagedResult<Auction> = await getData(queryString);

    searchStore.pageCount = result.pageCount;

    return result;
  });

  return (
    <>
      <Resource
        value={data.value}
        onPending={() => <h3>Loading</h3>}
        onResolved={(data) =>
          data.totalCount ? (
            <>
              <Filters />
              <div class='grid grid-cols-4 gap-6'>
                {data.results.map((auction: Auction) => (
                  <AuctionCard key={auction.id} auction={auction} />
                ))}
              </div>
              <div class='flex justify-center'>
                <AppPagination />
              </div>
            </>
          ) : (
            <EmptyFilter showReset />
          )
        }
      />
    </>
  );
});

// frontend/web-app/app/auctions/Listings.tsx
'use client';

import React, { useEffect, useState } from 'react';
import AuctionCard from './AuctionCard';
import { Auction, PagedResult } from '@/types';
import AppPagination from '@/app/components/AppPagination';
import { getData } from '@/app/actions/auctionActions';
import Filters from '@/app/auctions/Filters';
import { useParamsStore } from '@/app/hooks/useParamsStore';
import { shallow } from 'zustand/shallow';
import qs from 'query-string';
import EmptyFilter from '@/app/components/EmptyFilter';

export default function Listings() {
  const [data, setData] = useState<PagedResult<Auction>>();
  const params = useParamsStore(
    (state) => ({
      pageNumber: state.pageNumber,
      pageSize: state.pageSize,
      searchTerm: state.searchTerm,
      orderBy: state.orderBy,
      filterBy: state.filterBy,
      seller: state.seller,
      winner: state.winner,
    }),
    shallow
  );
  const setParams = useParamsStore((state) => state.setParams);
  const url = qs.stringifyUrl({ url: '', query: params });

  function setPageNumber(pageNumber: number): void {
    setParams({ pageNumber });
  }

  useEffect(() => {
    getData(url).then((data: PagedResult<Auction>) => {
      setData(data);
    });
  }, [url]);

  return !data ? (
    <h3>Loading...</h3>
  ) : data.totalCount ? (
    <>
      <Filters />
      <div className='grid grid-cols-4 gap-6'>
        {data.results.map((auction: Auction) => (
          <AuctionCard key={auction.id} auction={auction} />
        ))}
      </div>
      <div className='flex justify-center'>
        <AppPagination
          currentPage={params.pageNumber}
          pageCount={data.pageCount}
          pageChanged={setPageNumber}
        />
      </div>
    </>
  ) : (
    <EmptyFilter showReset />
  );
}
